### ISSUE TITLE
Could not find Kotlin on build.

### ISSUE THREAD

**Issue by TJGreen97** [twilio/twilio-video-app-android#111]
**Describe the bug**
Whenever I attempt to build the project I receive the error:
```
Could not find org.jetbrains.kotlin:kotlin-stdlib:1.4-M2-eap-23.
Required by:
    project :app > org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.72
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repository
2. Open in Android Studio

**Expected behaviour**
Build successfully and run on hardware/emulator.

**Video Android SDK:**
- 5.8.0

**Additional context**
I am new to Android app development so this may well be a basic issue; however, I believe I followed the documentation correctly, so it may just be a case of a small addition to the docs. But currently, I am still unable to build successfully.

**Comment by Alton09** [comment]
Hi @TJGreen97 . Please be sure to use Android Studio 4.0. Also, what build variant do you have selected when building the app? You'll want to make sure you have community build flavor selected. Please let us know if you are still running into that issue if the above isn't resolving the problem. Thanks!

**Comment by TJGreen97** [comment]
Hi @Alton09 . I am using Android Studio 4.0, I have also just realised the error occurs on each **sync** attempt rather than build.

**Comment by Alton09** [comment]
Have you tried deleting the contents of your gradle cache directory located at `$HOME/.gradle/caches`? You can also try deleting the `.idea/` dir and any .iml files in your project directory where you cloned the repo, which will refresh the IDE config files when you reopen the project in android studio.

**Comment by TJGreen97** [comment]
I ended up recloning the repo and it now works! I wonder if it was due to me using a fresh Android Studio install with nothing configured, I was configuring as I went so the cache probably needed clearing? Thanks

**Comment by Alton09** [comment]
Glad that worked for you! Perhaps the cache was in a weird state. I'll go ahead and close this issue for now.
