### ISSUE TITLE
How to mute and unmute other participant in room?

### ISSUE THREAD

**Issue by gokuCoder** [twilio/twilio-video-app-android#118]
I have implemented multi-party  video nowI want to mute and unmute some participant in room.

is there any way i can mute or unmute other participant in room

**Comment by Alton09** [comment]
Thanks for reaching out @gokuCoder ! Yes, there is a way to mute `RemoteAudioTrack`s with the video SDK. If you take a look at the [onAudioTrackSubscribed](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/sdk/RemoteParticipantListener.kt#L65) function within the `RemoteParticipantListener` class, there is a remoteAudioTrack parameter. In your application you can invoke [isPlaybackEnabled()](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/RemoteAudioTrack.html#isPlaybackEnabled--) with false passed in to mute the corresponding remote participant. Hope that helps!

**Comment by Alton09** [comment]
I'm going to close this issue for now. Please feel free to reopen if you are still running into issues. Thanks!
