### ISSUE TITLE
How to detect current speaker in video conference call?

### ISSUE THREAD

**Issue by gokuCoder** [twilio/twilio-video-app-android#119]
Hello there,

I want to get identify current speaker in conference call, is there any way i can get current speaker in group call?

I have read about [Detecting the Dominant Speaker](https://www.twilio.com/docs/video/detecting-dominant-speaker) and i'm using below code

```
try {
            val connectOptionsBuilder = ConnectOptions.Builder(ACCESS_TOKEN_SERVER)
                .enableDominantSpeaker(true)
                .roomName(roomName)
            room = Video.connect(context, connectOptionsBuilder.build(), roomListener)

            roomListener
        } catch (e: Exception) {
            handleTokenException(e)
        }

```

but i don't get any update inside onDominantSpeakerChanged() method

**Comment by Alton09** [comment]
Hi @gokuCoder ! It appears you have all the correct code setup to enable the Dominant Speaker feature, so I'm not sure why you are not receiving updates to `onDominantSpeakerChanged()`. We currently have this feature working in this video app. Please reference the [onDominantSpeakerChanged](https://github.com/twilio/twilio-video-app-android/blob/581c7597464daf6d4ed6b0c62f7a4a2b9ada73e1/app/src/main/java/com/twilio/video/app/sdk/RoomManager.kt#L108) implementation inside the `RoomManager` class to see how we've implemented it there. Essentially it sends an event that propagates down to the UI level to move the dominant speaker participant video thumbnail to the front of the list. Hope That helps! Feel free to reach out for additional help if needed.

**Comment by Alton09** [comment]
I'll go ahead and close this issue @gokuCoder . Feel free to open another if you need additional assistance. Thanks!
