### ISSUE TITLE
Min api 21

### ISSUE THREAD

**Issue by ArvindMewada** [twilio/twilio-video-app-android#137]
`Future<bool> connect(ConnectOptions connectOptions) async {
    assert(connectOptions != null);

    if (await requestPermissionForCameraAndMicrophone()) {
      final bool wasRequestSuccessful = await methodChannel.invokeMethod(
          'connect',
          <String, Object>{'connectOptions': connectOptions.toMap()});
      // print('Room Connected Successfully: $roomId');
      return wasRequestSuccessful;
    }
    throw Exception('Permissions not granted');
  }`

that code  give no any  response  in flutter  api min version 21
and API Level 24 that time it's working fine .

**Comment by Alton09** [comment]
Hi @ArvindMewada . I'm not sure what code you are referring to in this project and it appears to be related to flutter, which we do not support as part of this repository. I'm going to close this issue for now. Thanks!
