### ISSUE TITLE
Can we implement connection service with it to use Native Phone UI for Android?

### ISSUE THREAD

**Issue by tusharthinksys** [twilio/twilio-video-app-android#143]
Hi Guys,

I have some queries like:
 1. Can we implement connection service with Twilio video SDK?  If yes then please let me know how can we integrate Connection service(System managed) with it.
2. If there is any example related to Connection service implementation then please let me know.

**Comment by Alton09** [comment]
Hi @tusharthinksys ! Thanks for reaching out. We have yet to try integrating the connection service with the video SDK, but I'm sure it is possible. However, we do have an example getting this to work with the voice quickstart repo on [this branch](https://github.com/kbagchiGWC/voice-quickstart-android/tree/connection_service_example_makecall). Hope that helps!
