### ISSUE TITLE
Help wanted: Can't create camera capturers.

### ISSUE THREAD

**Issue by VanKhulup** [twilio/twilio-video-app-android#175]
Greetings! I've recently got quite a few crashes from the production version of the app because the app could not create camera capturers. I'm using [CameraCapturerCompat](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt) class from Twilio Video App to select appropriate CameraCapturer implementation. But it seems like few devices can't start image capturing. The range of affected OS versions is 7.0 - 10, and the affected devices are different.
![image](https://user-images.githubusercontent.com/49081243/103288769-57433b00-49ee-11eb-9123-7809da7eb6da.png)
Unfortunately, I don't have access to any of these devices, and my own test devices don't have this issue. I've managed to get this crash reproduced by removing the check for PRIVATE image format within [isCameraSupported](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/util/CameraCapturerCompat.kt#L104) method within CameraCapturerCompat. So my guess is that few devices that might not support this image format.

So my question is this - what is the reasoning, from SDK's point of view, to have this check?

**Comment by Alton09** [comment]
Hi @VanKhulup. I encountered the same bug you reported here after testing the `CameraCapturerCompat` class against some of the same devices you listed above. Take a look at #174 as it resolves this issue. Please let me know if you encounter anymore issues. Thanks!

**Comment by VanKhulup** [comment]
@Alton09 Thanks! We'll release hotfix ASAP and I'll let you know if this issue will still be present after that. Could you elaborate a bit on how this commit fixes the issue? The affected devices will fall back to legacy CameraCapturer, which would not require ImageFormat.PRIVATE to work? Or this format was not the reason for crashes?

**Comment by Alton09** [comment]
Hi @VanKhulup. So before this pull request, devices that use the legacy CameraCapturer instead of the Camera2Capturer were invoking the `getCameraCharacteristics(cameraId)` method within `isCameraIdSupported` which is only supported in the android camera2 api. I added a check that only camera2 compatible devices invoke it. Hope that helps!
