### ISSUE TITLE
Unable to run video:deploy

### ISSUE THREAD

**Issue by IgorGanapolsky** [twilio/twilio-video-app-android#198]
**Describe the bug**
I am following your README for CLI setup.  The deploy command doesn't work.

**To Reproduce**
1. Go to terminal
2. igorganapolsky@Igors-MacBook-Pro ~ % twilio rtc:apps:video:deploy --authentication passcode
3. **Error**:  » Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.
 ›   Error: EEXIT: 20003
 ›   Code: EEXIT
 
**Expected behavior**
It should start video:deploy

**Video Android SDK (please complete the following information):**
- Version: (e.g. 5.1.0)

**Additional context**

**Comment by Alton09** [comment]
Hi @IgorGanapolsky ! Thanks for reaching out. Have you tried the Possible Solutions outlined in that error code link above? 
>Verify the Account SID and Auth Token are correct
Verify the correct Account is being accessed
Ensure the Account is active, not suspended or closed
Ensure no extra characters or spaces are being included
Ensure JWT is only used with API Key

**Comment by IgorGanapolsky** [comment]
I believe I tried all of the above steps.  Question:
> Ensure JWT is only used with API Key

What is that?

**Comment by Alton09** [comment]
You only need to worry about that if you are using access tokens. [Here's some documentation](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens) that goes into more detail on that subject. However, with this command you can work around that by setting the following environment variables:
```
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key
```

**Comment by IgorGanapolsky** [comment]
Is this part of */twilio-cli/config.json *file?

**Comment by Alton09** [comment]
Hmm not sure about that config file. If you are using Mac OS you can set the environment variables in your `~/.bashrc` file. That way they get set every time you start a new session in the terminal before you interact with the Twilio CLI. Hope that helps!

**Comment by IgorGanapolsky** [comment]
Hmm, my Mac doesn't even have a **~/.bashrc** file.  All I have is **~/.bash_profile**.  Do you use ~/.bashrc yourself?
