### ISSUE TITLE
How to add event like call ringing or incoming call?

### ISSUE THREAD

**Issue by premchand-algo** [twilio/twilio-video-app-android#207]
I need to add call ringing at the receiver end for the incoming video call in the android app.

How I can achieve it by Twilio?

Thank you.

**Comment by Alton09** [comment]
Hi @premchand-algo ! Thanks for reaching out. The Video Android SDK doesn't provide this functionality, but you can use Twilio Notify with Firebase Cloud Messaging to achieve this. Please see this [readme](https://github.com/twilio/video-quickstart-android/tree/master/exampleVideoInvite) to learn how to get this working.
