### ISSUE TITLE
Login not possible with access token

### ISSUE THREAD

**Issue by metizror** [twilio/twilio-video-app-android#213]
My code working fine with the passcode. But I want to Login with the access token but it will not work for me? Please explain the more details for the same

**Comment by Alton09** [comment]
Hi @metizror. Thanks for reaching out! This is pretty straightforward to do. All that is needed is to pass the access token to the [ConnectOptions.Builder(AccessToken)](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/ConnectOptions.Builder.html#Builder-java.lang.String-) constructor and pass the connect options instance to the [Video.connect()](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/Video.html#connect-android.content.Context-com.twilio.video.ConnectOptions-com.twilio.video.Room.Listener-) method.

**Comment by Alton09** [comment]
Closing this one due to inactivity
