### ISSUE TITLE
This code available in java? 

### ISSUE THREAD

**Issue by metizror** [twilio/twilio-video-app-android#214]
We are not much familiar with kotlin and we develop our chat app with Twilio conversation in java(android). And we want to add video calls in-app. So any Java code available?

**Comment by Alton09** [comment]
Hi @metizror . This app is primarily written in Kotlin. We do however have a Java quickstart example [here](https://github.com/twilio/video-quickstart-android#quickstart). Hope this helps!

**Comment by aaalaniz** [comment]
Hey @metizror 

We do not plan to provide a Java reference app.

Thank you for your feedback!
