### ISSUE TITLE
Is there is any way to find out whose video is rendering in a primary view?

### ISSUE THREAD

**Issue by vjvk** [twilio/twilio-video-app-android#216]
### Description
Please help me out to find whether the local video view/participant view showing on the PrimaryView, we needs to find the current primary rendering video belongs to which participants?

As I am having multiple participants with video rendering on the bottom of the screen in thumbnail view.
But I would like to know, which participant has rendering in the PrimaryView(i.e in the Maximized view)

**Comment by vjvk** [comment]
Hi,
Yes, I have gone through those code. But I needs to pin the local participants in the primary view always. That primary video view should not to change whenever the new participants are joining.
So is there any way to achieve this. Kindly do needful.

**Comment by Alton09** [comment]
Yes, so the video app actually has this feature as well. If you click on any video thumbnail, it will pin that participant's video in the primary view. The [ParticipantManager](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/participant/ParticipantManager.kt) class contains the logic to make this work.

**Comment by vjvk** [comment]
Yes, I got an idea on that class. Thanks.
