### ISSUE TITLE
Hi sir, In twilio android -android is not connecting by using Token. i didn't used passcode. while, generating token, my token function is called.

### ISSUE THREAD

**Issue by BhargaviSunku** [twilio/twilio-video-app-android#222]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/twilio-video-app-android/issues)
>  * [Changelog](https://github.com/twilio/twilio-video-app-android/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Android Device (please complete the following information):**
 - Device: (e.g. Pixel 4)
 - API Version: (e.g. API 29)

**Video Android SDK (please complete the following information):**
- Version: (e.g. 5.1.0)

**Additional context**

**Comment by vjvk** [comment]
BhargaviSunku,
Instead of using the passcode, you can pass your access_token to the class `ConnectOptionsFactory` to connect the room.
Instead of this, 
` val token = tokenService.getToken(identity, roomName)`

you can pass your access token like this.
` val token = YourTokenHere`

**Comment by Alton09** [comment]
@BhargaviSunku It is highly recommended to use the passcode approach by following [this guide in the README](https://github.com/twilio/twilio-video-app-android#deploy-twilio-access-token-server). Otherwise, you can modify the source code like @vjvk suggested above to inject your own access token.
