### ISSUE TITLE
Camera freezes when flipping from Front to Back

### ISSUE THREAD

**Issue by esathamzaj** [twilio/twilio-video-app-android#238]
This bug happened on a Samsung Galaxy Note Fan Edition running android 6.0.
I use these versions:

 implementation "com.twilio:video-android:6.3.1"
 implementation "com.twilio:video-android-ktx:6.3.1"
 implementation "com.twilio:audioswitch:1.1.2"

**Comment by afalls-twilio** [comment]
@esathamzaj thank you for filing a but report, can you please tell me more about the bug you experienced?
