### ISSUE TITLE
Screen comes as black screen randomly for remote participants

### ISSUE THREAD

**Issue by saad100104006** [twilio/twilio-video-app-android#243]
**Screen comes as black screen randomly for remote participants**
In the video call, the screen comes as a black screen randomly from remote participants. It doesn't always happen but happens randomly. Faced more frequently in version 7.0.0 and in version 6.0.0 it's happening randomly.

**To Reproduce**
Doesn't occur reliably, but mostly happens in the first-time call.
Connect to the room
Remote participant connect to room with/without videoTrack published

**Expected behavior**
The remote participant screen shouldn't go off as a black screen.

**Screenshot**
![Screenshot_20211210-133154](https://user-images.githubusercontent.com/8910479/145931962-015ac605-16c3-46e0-a110-bcbe65c9492e.jpg)

**Android Device:**
 - Device: ( One Plus 8T)
 - API Version: (e.g. API 30)
 Remote participant is on JavaScipt Twilio SDK and local participant on Android

**Video Android SDK:**
- Version: (6.0.0 & 7.0.0)

**Comment by geek2driod** [comment]
Hey, did you guys found any solution for this issue?

**Comment by afalls-twilio** [comment]
@geek2driod & @saad100104006 sorry about the late response and thank you for filing this issue. This can happen when you are streaming in an area with poor network coverage. You can enable stats and see if there is high packet loss.
