### ISSUE TITLE
Twilio Video Calling Android Java or Kotlin

### ISSUE THREAD

**Issue by SHUBHAMGUPTA123456** [twilio/twilio-video-app-android#255]
Hello,
I want to use Twilio Video calling functionality, but I'm unable to find proper step for implement video calling feature in android via Kotlin or Java and also not getting any reference according to this.
Kindly send me the link you h've step wise implementation of video calling using Kotlin/Java or do something else for helping me.

Thank You!

**Comment by afalls-twilio** [comment]
@SHUBHAMGUPTA123456 have you checked out the quickstarts, there you will find examples in both kotlin and java.
https://github.com/twilio/video-quickstart-android
