### ISSUE TITLE
Upgrade to the latest WebRTC version M10x for Twilio Video SDK

### ISSUE THREAD

**Issue by jeryini** [twilio/twilio-video-app-android#260]
**Is your feature request related to a problem? Please describe.**
In the 7.x [change logs](https://www.twilio.com/docs/video/changelog-twilio-video-android-v7) for Twilio Video Android SDK it says that initial 7.0.0 release version was upgraded to use Chromium WebRTC 88. Changelogs for other versions don't mention additional upgrade. The Chromium WebRTC version is already at [M107](https://groups.google.com/g/discuss-webrtc/c/StVFkKuSRc8) and since M88 version, lots of changes were added to the library.

**Describe the solution you'd like**
Upgrade to more latest WebRTC M10x version, as since M88 they have included quite a lot of bugfixes.

**Describe alternatives you've considered**
No alternative as the library needs to be upgraded in the Twilio Video itself.

**Additional context**
Newest Chromium WebRTC M107 [release notes](https://groups.google.com/g/discuss-webrtc/c/StVFkKuSRc8).

**Comment by seancoleman2** [comment]
Hi @jeryini - thanks for the feature request! We are currently working to upgrade our iOS and Android SDKs to M105. We are aiming to have this released sometime in Q1. 

I'll close this ticket for now, but please do reach out if you have any other questions. Thanks!
