### ISSUE TITLE
How do we get RTCStatsReport using twilio android sdk.

### ISSUE THREAD

**Issue by krunalspearline** [twilio/twilio-video-app-android#261]
- I would like to know that how we can get RTCStatsReport using twilio android sdk.
- I have went throw the com.twilio.video.Room.getStats(statsListener) but this is providing different report not similar like RTCStatsReport (libwebrtc stats report).
- I have found method getRtcStats(@NonNull RtcStatsListener rtcStatsListener) inside the Room class but this method is not public. Is there any other way where we can get the List<RTCStatsReport>?

I really appreciate your help for the same. Thanks in advance!!

**Comment by ocarevs** [comment]
@krunalspearline For now this is the only way to get RTCStatsReport. You will need to use Java reflection to access the pacakge-private method. Also you will need to create com.twilo.video package in your project where you would call the getRtcStats method.
