### ISSUE TITLE
Audio delay on low network

### ISSUE THREAD

**Issue by pkdhankher** [twilio/twilio-video-app-android#269]
Dear Team,

I have been experiencing an issue during video calls. Whenever a participant with low network connectivity joins the meeting room, there is a noticeable delay of 1-2 seconds in the audio for all participants in the meeting, not just the participant with low connectivity.

I have taken steps to address this issue by prioritizing the audio track for participants with low network connectivity, but unfortunately, it has not resolved the problem. As such, I am seeking your assistance in resolving this issue.

If any of you have experience in troubleshooting similar issues or have any suggestions on how we can overcome this, please share your insights.

Thank you in advance for your help and cooperation.

Best regards,

**Comment by afalls-twilio** [comment]
@pkdhankher Thanks for the report and sorry for the delayed response.  this is probably due to the poor network condition causing the setup of the audio and video channels to take a long time. This includes the SDP negotiations, etc..
