### ISSUE TITLE
Camera2Capturer is not supported on this device

### ISSUE THREAD

**Issue by SebPawp** [twilio/twilio-video-app-android#273]
**Describe the bug**
SDK crashes when trying to start a video chat.
Happened with 2 devices, same error.

# Device 1
***Android Device (please complete the following information):***
 - Device: [CPH1613](https://www.gsmarena.com/oppo_f3_plus-8613.php)
 - API Version: `Android 6.0.1 (23)`

**Video Android SDK (please complete the following information):**
- Version: `7.6.1`

**Additional context**
```kotlin
java.lang.IllegalStateException: Camera2Capturer is not supported on this device
    at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
    at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:219)
    at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:192)
```

---

# Device 2
***Android Device (please complete the following information):***
 - Device: [SM-T560NU](https://www.gsmarena.com/samsung_galaxy_tab_e_9_6-7295.php)
 - API Version: `Android 7.1.1 (25)`

**Video Android SDK (please complete the following information):**
- Version: `7.3.0` (not sure if it happens on `7.6.1`)

**Additional context**
```kotlin
java.lang.IllegalStateException: Camera2Capturer is not supported on this device
    at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
    at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:219)
    at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:192)
```
---

I see in the SDK you have :
```kotlin
public static boolean isSupported(@NonNull Context context) { ... }
```
but I don't see any mention in the docs or anything.

Do we first need to check if supported? What would be the fallback if not supported?

Thank you.

**Comment by afalls-twilio** [comment]
@sebPawp Sorry for the delayed response, there are...
`CameraCapturer` - 'old' Camera API, works on everything
`Camera2Capturer` - 'new' Camera API, works on newer devices

using `isSupported` one can make a generic capturer that wraps both and that test if camera2 or camera is available and then selects it based on its availability.
