### ISSUE TITLE
Error on CLI after Deploy Twilio Access Token Server

### ISSUE THREAD

**Issue by goncaloflf** [twilio/twilio-video-app-android#69]
**Describe the bug**
When running the README.md of this application, running the command `twilio rtc:apps:video:deploy --authentication passcode` will result in an error `twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues`.

**To Reproduce**
1. Create a new twilio account
2. Follow the steps on [Deploy Twilio Access Token Server](https://github.com/twilio/twilio-video-app-android#deploy-twilio-access-token-server)
4. See error after executing step 3

**Expected behavior**

**Additional context**
Pop-OS 19.04 x86_64
Twilio CLI: twilio-cli/1.12.0 linux-x64 node-v12.16.1
NodeJS: 12.16.1
npm: 6.13.4
nvm: 0.35.3

Running with the debug flag gives:

`twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /home/gferreira/.twilio-cli/config.json
[DEBUG] Using profile: goncalo-pop
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.42.0, node.js v12.16.1, linux 5.0.0-21-generic x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 01 Apr 2020 22:11:32 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQea6e243479e14b04bf18e1538dc8c856","twilio-request-duration":"0.034","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSf9c1875b44881004a043b620f0bba67b/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.42.0, node.js v12.16.1, linux 5.0.0-21-generic x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 01 Apr 2020 22:11:32 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ5ef2a61053ca4e24acdc9a5386a2aa35","twilio-request-duration":"0.034","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/home/gferreira/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:76:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/home/gferreira/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/home/gferreira/.twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/home/gferreira/.nvm/versions/node/v12.16.1/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/home/gferreira/.nvm/versions/node/v12.16.1/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/home/gferreira/.nvm/versions/node/v12.16.1/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)`

**Comment by goncaloflf** [comment]
I've tried using `twilio login` and two ENV VARS methods described in [here](https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile), both without success

**Comment by Alton09** [comment]
Hi @goncaloflf,

Thanks for reaching out! Do you mind updating to the latest version by running the following commands?

```
twilio plugins:update
twilio rtc:apps:video:delete
twilio rtc:apps:video:deploy --authentication passcode
```

**Comment by goncaloflf** [comment]
Cheers @Alton09 , thank you for the quick response! That fixed my problem, thank you so much. Do you believe it's worth mentioning that on the README? :thought_balloon:

**Comment by Alton09** [comment]
Glad that helped @goncaloflf! We'll be sure to update the README to include that information. Thanks for the feedback 👍
