### ISSUE TITLE
Usages Detail is not clear

### ISSUE THREAD

**Issue by abhi8702** [twilio/twilio-video-app-android#73]
I run this code. I can not login to the app. How to get the name and passcode and in the sample. which credentials I have to change to use this sample in my app. Please help me on this

**Comment by Alton09** [comment]
Hi @abhi8702 ,

Thanks for reaching out! The name can be whatever you want it to be as it is just an identifier used when joining a video room. The passcode comes from the Twilio CLI, which is generated after following [these steps](https://github.com/twilio/twilio-video-app-android#deploy-twilio-access-token-server). Were you able to successfully follow these steps to generate a passcode to use in the app?

**Comment by Alton09** [comment]
Closing for now @abhi8702. Please free to reach out again if you are having any more issues with the Twilio CLI setup.

**Comment by cjf12harry** [comment]
I am trying out with the sample. As soon as I ran the the quickstart sample app, it goes into the camera view, with "Connect to a Room" button and other control buttons. There is no log in or place to input passcode. Where should I put the passcode and webapp link in the android app? In local.properties?

**Comment by Alton09** [comment]
Hi @cjf12harry. For instructions on how to get up and running with this app, please refer to the [Getting Started Section](https://github.com/twilio/twilio-video-app-android#getting-started) in the readme. It has instructions on how to generate a passcode that can be used in this app.

If you run the `community` product flavor, you should see the login screen asking for your name and passcode.
