### ISSUE TITLE
Couldn't find DSO to load: libfb.so

### ISSUE THREAD

**Issue by grago** [twilio/twilio-video-app-android#75]
When trying to login, i get the following exception: 
"couldn't find DSO to load: libfb.so"

Looking a little bit i found that this has to do with SoLoader library.  I tried to upgrade the library but i can't find the implementation entry in app build.gradle file.

**To Reproduce**
1. Open app
2. Enter username and passcode
3. Click "Login" 

**Expected behavior**
Navigate to lobby activity

**Android Device (please complete the following information):**
 - Device: Motorola One
 - API Version: 28

**Comment by Alton09** [comment]
Hi @grago. Thanks for reporting this issue. We will look into it and report back with our findings.

**Comment by Alton09** [comment]
@grago Is this error crashing the application and preventing you from proceeding to the RoomActivity? Or is this error just being logged to Logcat? If it is causing a crash, do you mind sharing the Logcat file? Thanks!

**Comment by grago** [comment]
thanks @Alton09 I should have mentioned, this is only happening on the release build. So i haven't been able to see the error in Logcat (but i managed to print it out so i could see the error on screen).

The error causes an exception right after the login action on Login Activity:

```
    private void login(String identity, String passcode) {
        preLoginViewState();

        disposable.add(
                authenticator
                        .login(new CommunityLoginEvent(identity, passcode))
                        .observeOn(AndroidSchedulers.mainThread())
                        .doFinally(this::postLoginViewState)
                        .subscribe(
                                loginResult -> {
                                    if (loginResult instanceof CommunityLoginSuccessResult)
                                        startLobbyActivity();
                                    else {
                                        handleAuthError(loginResult);
                                    }
                                },
                                exception -> {
                                   // EXCEPTION IS HANDLED HERE //
                                    handleAuthError(null);
                                    Timber.e(exception);
                                }));
    }
```

As a side note, i've removed the SoLoader library usage, and the error went out. Obviously all the sensitive data is not being encrypted on SharedPreferences though.

**Comment by Alton09** [comment]
Thanks for the detailed information @grago. The release and internal build variants are for internal Twilio use only. You'll need to use the community build variant. There is more information about the build variants in the [Build section](https://github.com/twilio/twilio-video-app-android#build) of the readme. Please let us know if you are having issues with the community variant as well.

**Comment by grago** [comment]
Yes i was aware of the build flavors, however there's no mention about the debug and release versions. So it's not possible to build a release version of this app?

**Comment by Alton09** [comment]
I see, thanks for clarifying. We currently do not support the release build type for the community flavor. Is there a reason why you'd want to build a release version for this app? Normally, devs deploy this app on a device as a demo of the video SDK and not being concerned with using a specific build type.

We can certainly be clearer in the readme about which build types are supported though, I appreciate that feedback.

**Comment by grago** [comment]
Initially, i wanted to try out the Twilio video service on several devices, in order to test the overall video quality and stability of the service. 

Later i'd like to modify the app heavily in order to create my own product. Since this demo app is so well constructed and tested, it would be a shame to have to create an app from scratch, in my opinion, as it would allow to have a Twilio based product up and running very quick.

Would it be an option to allow release builds at some point? Is it something you don't allow from a license perspective, or it's just a technical obstacle?

Thanks!

**Comment by Alton09** [comment]
Thanks for sharing that information @grago. Your use case makes sense and there is definitely no reason why we can't support it. I went ahead and added this task to our next sprint to resolve this crash. I'll close this issue as soon as a fix is out. Thanks again for raising this issue!

**Comment by grago** [comment]
That's awesome @Alton09 i really appreciate that!! Thank you very much for your help.

**Comment by Alton09** [comment]
Hi @grago. I went ahead and merged a fix for this crash in the master branch. I'll close this issue for now, but feel free to reach out if you are experiencing any more issues. Thanks!

**Comment by grago** [comment]
I can confirm that release build is working perfectly now. Thanks a lot for your support!

**Comment by Alton09** [comment]
No problem! Glad to hear that it's working for you.
