### ISSUE TITLE
How to handle incoming call when receiver is busy with another call

### ISSUE THREAD

**Issue by ghost** [twilio/twilio-video-app-android#76]
When receiver is busy with another voice or video call, i.e user's device microphone and camera is already acquired by another app. If you can suggest how to handle this situation.
Also, is there any way to detect from caller's end that receiver is busy with another call?

**Comment by aaalaniz** [comment]
Hey @sunit-navsoft 

I moved your issue from the Quickstart to our collaboration application. We will do some UX research based on other collaboration apps out there and get back to you with guidance. Thank you for bringing this to our attention!
