### ISSUE TITLE
Using Custom Camera Source

### ISSUE THREAD

**Issue by Sujith-PS** [twilio/twilio-video-app-android#83]
Is it possible to use a custom camera source instead of using the camera source from the SDK when 
 initializing the localvideo track 

cameraCapturer = new CameraCapturer(this, CameraSource.FRONT_CAMERA);
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, cameraCapturer);

My usecase is to add a background/bokhe effect to the video before it is rendering on the view.So the user have a control over this.like he can turn on /off his background blurring.So i though about modifying the camerasource before it is giving to a localvideotrack.I saw most of the cameracapture functions expecting a camerasource of type same from the SDK.Can you recommend some suggestions for this

**Comment by aaalaniz** [comment]
Hey @Sujith-PS 

This should be possible by writing your own custom `VideoCapturer` or extending the `CameraCapturer` or `Camere2Capturer` and intercepting the camera frames before they are sent to the SDK media engine. Both approaches are non-trivial tasks. I suggest you reference our [custom video capturer](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoCapturer) example to understand what is involved in writing a custom video capturer.

If you'd like to explore further, I suggest creating a separate Github project where we can prototype the use case together.

Enabling this type of use case is not currently on our roadmap, so I will close this issue. However, we will certainly try to help where possible.

Thanks!

**Comment by Sujith-PS** [comment]
hey @aaalaniz 
 i had tried the above sample for custom camera [source](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomVideoCapturer) .its only working with linerlayout/imageview kind views.When i tried to give a actual cameraview/openCVcamera to the customcapture ,getting a darkscreen in the renderpart

 _localVideoTrack = LocalVideoTrack.create(this, true, new ViewCapturer(**CameraView**));
   localVideoTrack.addRenderer(videoView);_

Is there any call back inside the CameraCapture to get the Frames from the Actual Camera Source?Can you suggest any sample code demonstrate the  manipulation of  frames from camera Source before it is giving to the SDK media engine?

**Comment by aaalaniz** [comment]
Hey @Sujith-PS 

If you extend the CameraCapturer or Camera2Capturer classes, you should be able to override `startCapture` and proxy the frames delivered to the provided [VideoCapturer.Listener](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/VideoCapturer.Listener.html).

The steps should work as follows:

1. Extend CameraCapturer or Camera2Capturer
2. Override `startCapture` and create your own VideoCapturer.Listener which wraps the listener provided from the media engine. (`super.startCapture(videoFormat, yourCustomCapturerListener`)
3. In your capturer listener process the `VideoFrame` and after the process proxy the modified frame to the encapsulated listener provided from the media engine.
