### ISSUE TITLE
Audio and video preview is not working on AndroidX

### ISSUE THREAD

**Issue by amirocpc** [twilio/twilio-video-app-android#86]
**Description**
We are using Twilio Android programmable sample which works fine but in AndroidX based on the error logs it seems like **audioDeviceSelector.activate();** is crashing and therefore after participants join a room they don't see or hear each other. 

Below is the sample code were AndroidX is used:
https://github.com/mukeshocpc/TwillioSample

**Device Info**
Galaxy Note8
Model #: SM-N950U
Android Version: 7.1.1

minSdkVersion 21
targetSdkVersion 29
versionCode 1
versionName "1.0"

'videoAndroid'       : '5.6.0',
'audioSwitch'        : '0.1.0'

**Comment by Alton09** [comment]
Hi @amirocpc. https://github.com/twilio/audioswitch is the correct place to report this issue. I see you have opened a ticket there - twilio/audioswitch#17, closing this as a duplicate.
