### ISSUE TITLE
Mute audio/video when phone call received and picked

### ISSUE THREAD

**Issue by him2016** [twilio/twilio-video-app-android#87]
I have been trying to integrate Twilio SDK in my app. I came across a scenario where I need to mute audio and stop video capture when phone call received. Does the SDK provide any callback and how do I handle it?

**Comment by Alton09** [comment]
Hi @him2016 ! Thanks for reaching out. This scenario is not handled by the SDK. However, we are planning to add this feature to the video app to help demonstrate how to handle this scenario in a production collaboration video app. It will essentially respond to system phone call events using the Android [PhoneStateListener](https://developer.android.com/reference/android/telephony/PhoneStateListener#LISTEN_CALL_STATE) class. In the meantime, [here](https://stackoverflow.com/a/13396210/5163090) is a thread on stackoverflow that demonstrates how to handle this.

**Comment by him2016** [comment]
Thanks for the prompt reply. I will try this. Also if possible, can you let me know by when it will be demonstrated in the sample app..?

**Comment by Alton09** [comment]
Yes, I'll make sure to close this issue once it has been implemented in the app.

**Comment by him2016** [comment]
ok thanks.. looking forward to it..

**Comment by VanKhulup** [comment]
Are there any updates on this question? What is the recommended way to handle this scenario on Twilio side? The only possible way I see is to manually mute all remote/local participant's audio tracks in the room and remembering their state to properly restore them when the Twilio session is restored.

**Comment by Alton09** [comment]
Hi @VanKhulup . This one is still in our backlog for this app. However, it shouldn't be too bad to implement. Checkout this comment:

> Hi @him2016 ! Thanks for reaching out. This scenario is not handled by the SDK. However, we are planning to add this feature to the video app to help demonstrate how to handle this scenario in a production collaboration video app. It will essentially respond to system phone call events using the Android [PhoneStateListener](https://developer.android.com/reference/android/telephony/PhoneStateListener#LISTEN_CALL_STATE) class. In the meantime, [here](https://stackoverflow.com/a/13396210/5163090) is a thread on stackoverflow that demonstrates how to handle this.

After receiving the phone call event from a broadcast receiver, you should then be able to mute the local audio and video tracks with logic like this...

https://github.com/twilio/twilio-video-app-android/blob/f883e8d68c997d9e8f484771f2797be2802a8102/app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt#L77

https://github.com/twilio/twilio-video-app-android/blob/f883e8d68c997d9e8f484771f2797be2802a8102/app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt#L107

We are open for any pull requests from the community if anyone gets to this before we do 😃

**Comment by Alton09** [comment]
Closing this issue as it will be covered in #212

**Comment by KishanViramgama** [comment]
@Alton09 @him2016 
Hello I'm trying to implement this functionality but it's not working only the video is paused but the audio is not paused/disabled if any other way then let me know about this.
