### ISSUE TITLE
Audio video not working after upgrading to AndroidX

### ISSUE THREAD

**Issue by mukeshocpc** [twilio/twilio-video-app-android#89]
https://github.com/mukeshocpc/TwillioSample/blob/master/app/src/main/java/indiqube/com/twilliotest/VideoActivity.kt

Audio and video not working after upgrading to AndroidX
Device specification:
![issue](https://user-images.githubusercontent.com/30304398/82080030-7a400980-9701-11ea-8e1f-e1d60caa0b93.jpeg)

      minSdkVersion 21
      targetSdkVersion 29
      versionCode 1
      versionName "1.0"

       'videoAndroid'       : '5.6.0',
       'audioSwitch'        : '0.1.0'

**Comment by Alton09** [comment]
Hi @mukeshocpc. This appears to be the same issue you reported in the AudioSwitch library [here](https://github.com/twilio/audioswitch/issues/17). Please take a look there for feedback about the issue you are experiencing. Thanks!

**Comment by mukeshocpc** [comment]
this don't solve my problem i remove audio switch library then also video is not rendering.
this can be solved by if u just see the code. please don't close a ticket util my problem is fixed.
https://github.com/mukeshocpc/TwillioSample/blob/master/app/src/main/java/indiqube/com/twilliotest/VideoActivity.kt

**Comment by Alton09** [comment]
Hi @mukeshocpc . The reason why you are not able to see the other remote participant's video, is because you need to supply a unique identity for each participant that joins a room. Replace your request builder in `VideoActivity.kt` `retrieveAccessTokenfromServer()`with the following code snippet in your project and it will resolve your problem.

```
        val request = Request.Builder()
            .url("$ACCESS_TOKEN_SERVER$roomName&identity=joe${UUID.randomUUID().toString().takeLast(4)}")
            .build()
```

**Comment by mukeshocpc** [comment]
i have implemented that logic in server
<img width="549" alt="Screen Shot 2020-05-21 at 4 57 49 PM" src="https://user-images.githubusercontent.com/30304398/82554949-7dfde100-9b84-11ea-8307-28c9565648b3.png">
