### ISSUE TITLE
Permission Denial Causes Crash

### ISSUE THREAD

**Issue by cyodrew** [twilio/twilio-video-app-android#98]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/twilio-video-app-android/issues)
>  * [Changelog](https://github.com/twilio/twilio-video-app-android/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**
When a user denies camera or audio permissions and chooses either the toggle local video/audio buttons, the app crashes.

**To Reproduce**
1. Open the app and log in normally using name and passcode
2. Deny either the audio permission, camera permission, or both
3. Tap the toggle local audio or toggle local video buttons on the bottom right 
4. The app will crash with an `IllegalStateException` due to `LocalAudioTrack` or `LocalVideoTrack` being called without the proper permissions granted

**Expected behavior**
A user might expect a message to display notifying them to enable the permissions in the settings for the application in order to toggle the video/audio.

**Screenshots**

**Android Device (please complete the following information):**
 - Device: Pixel 3
 - API Version: API 29

**Video Android SDK (please complete the following information):**
- Version: 5.1.0

**Additional context**

**Comment by Alton09** [comment]
Thanks for creating this issue @cyodrew! I was able to reproduce the crash as well. I'll try to get a fix in with a feature branch I'm currently working on. If not, I'll add this issue to our backlog and get this fixed in one of our upcoming sprints.

**Comment by Alton09** [comment]
Hi @cyodrew . This bug was fixed as part of #114 . I'll close this issue for now, but please reach out if you are still experiencing issues. Thanks!
